export const FETCH_POKEMON_BEGIN = "FETCH_POKEMON_BEGIN";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";

export const FETCH_POKEMON_DETAILS_BEGIN = "FETCH_POKEMON_DETAILS_BEGIN";
export const FETCH_POKEMON_DETAILS_SUCCESS = "FETCH_POKEMON_DETAILS_SUCCESS";
export const FETCH_POKEMON_DETAILS_FAILURE = "FETCH_POKEMON_FAILURE";

export const ADD_TO_SQUAD = "ADD_TO_SQUAD";
